apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: oa7xglknr-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/oa7xglknr-dotnet-basic-gitops